fedora-copr/logdetective-website

README.md, backend/README.md, docker-compose.prod.yaml, docker-compose.yaml, docker/production/Dockerfile, frontend/package-lock.json, frontend/package.json, frontend/public/index.html, frontend/public/layout.html, openshift/README.md, openshift/log-detective.yaml
The new name is Log Detective and `log-detective`
=> Rename the project to Log Detective

docker-compose.yaml
This patch merges two environment sections into one, allowing for compose file unmarshalling to finish.
#26
=> Removing duplicated keys in compose file

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, README.md
These changes should help us keep certain coding standard while the project grows.
=> Pre-commit application

.github/workflows/new-issues-to-board.yml
=> workflows: move new issues to our kanban board to needs-triage

frontend/src/app/contribute.cljs
=> Add consent that data are under CDLA-Permissive-2.0 license.

docker/production/Dockerfile
using multi-stage builds:
https://docs.docker.com/build/building/multi-stage/
Current size: 963 MB
Fixes #9
=> dockerfile: split production to two images

README.md, openshift/log-detective.yaml
http://log-detective.com/
http://logdetective.com
=> openshift: add routes for our production hostnames

backend/fetcher.py
With the output saved, we can query the exception and give something more precise as an error.
Optionally, we can disable detailed reporting in production, just to be sure we are not leaking.
=> Covering subprocess errors with exceptions

backend/fetcher.py, docker/backend/Dockerfile
this PR is based on mhroncok's feedback about koji tasks
and because this also drops koji cli dependency, also Fixes #20
=> backend: fix koji task id fetching - CLI can fetch only successfull tasks

backend/fetcher.py
=> backend: dont pass fake spec for url upload, use empty one

.github/workflows/docker-publish.yml, openshift/README.md
Builds will now happen only on tags. The image will be also tagged by hash and as latest.
=> Build and publish workflow adjustment

.pre-commit-config.yaml, frontend/README.md, frontend/shadow-cljs.edn, frontend/src/app/components/accordion.cljs, frontend/src/app/components/jumbotron.cljs, frontend/src/app/contribute.cljs, frontend/src/app/contribute_atoms.cljs, frontend/src/app/contribute_events.cljs, frontend/src/app/contribute_logic.cljs, frontend/src/app/core.cljs, frontend/src/app/editor/core.cljs, frontend/src/app/helpers.cljs, frontend/src/app/homepage.cljs, frontend/src/app/homepage_validation.cljs, frontend/src/app/review/core.cljs, frontend/src/app/three_column_layout/core.cljs
I don't have any experience with ClojureScript linters yet, `M-x indent-region` was good enough so far. But I want to see how they work.
=> Setup linter for ClojureScript

docker/production/Dockerfile
this should be part of 5e3cab8bc18ba46b5e907c6f39ca37e946d7beda
=> docker: fix the new hierarchy in prod dockerfile

backend/src/api.py, backend/src/constants.py, backend/src/fetcher.py
=> Link Packit builds

backend/src/schema.py, backend/tests/conftest.py
=> backend: store the text user selected as interesting snippet

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, backend/src/api.py, frontend/src/app/homepage.cljs
the pre-commit github action behaves weirdly sometimes #63
using pre-commit-ci app (or just running it via command in github action) should solve this
=> pre-commit: disable autofixes

frontend/src/app/contribute.cljs, frontend/src/app/contribute_events.cljs, frontend/src/app/helpers.cljs, frontend/src/app/homepage.cljs
=> frontend: display an error when access to localStorage is blocked

frontend/src/app/contribute.cljs
There's no button labeled "Annotate selection", the button is simply labeled "Add".
=> Update instructions in contribute.cljs

frontend/public/layout.html, frontend/src/app/review/core.cljs
=> frontend: delete dangling slash to avoid redirects

docker/backend/Dockerfile, docker/frontend/Dockerfile, docker/production/Dockerfile
so that the frontpage gif is present in the image
Fixes #148
Still testing this locally with the prod image.
=> install git-lfs in our containers

backend/src/api.py, backend/src/exceptions.py, backend/src/store.py, frontend/src/app/review/core.cljs
=> Put result ID into review URL

backend/src/api.py, frontend/public/app.html, frontend/public/contribute.html, frontend/public/css/contribute-and-review.css, frontend/public/css/prompt.css, frontend/public/css/style.css, frontend/public/layout.html, frontend/src/app/core.cljs, frontend/src/app/prompt/core.cljs
I am adding a first version of the Log Detective service prompt. There is not a link on the website yet because the feature isn't finished You can access it via http://127.0.0.1:5020/explain
The frontend is fully-functional, few things are remaining:
- It needs to be finished from a visual standpoint
- The input form uses only a simple textarea, the integration with Copr, Koji, etc that we have on our homepage needs to be added
The backend part is only a mock implementation, always returning the same hardcoded values for every input. Somebody needs to implement an actual communication with the Log Detective service.
=> First draft of the Log Detective service prompt

backend/src/api.py, backend/src/spells.py
=> backend: tar also reviews for download

openshift/log-detective.yaml
https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
=> openshift: set SERVER_URL

frontend/src/app/prompt/core.cljs
There was a syntax error since PR #199 ... also the file upload button is not implemented yet.
=> Small fixes for the prompt

frontend/src/app/prompt/core.cljs
It's not perfect, I'm looking for feedback :)
=> explain: add disclaimer

frontend/src/app/homepage.cljs
The code works with task id, not build id.
=> correct desription of Koji form

backend/src/api.py
See https://github.com/fedora-copr/logdetective/pull/139
=> backend: the server API changed and some keys were renamed

frontend/src/app/components/snippets.cljs, frontend/src/app/contribute.cljs, frontend/src/app/contribute_atoms.cljs
=> frontend: change 'add snippet' color and tooltip when it can be used

frontend/src/app/review/core.cljs
Fix https://github.com/fedora-copr/logdetective/issues/218
=> frontend: fix swapped snippet comments

backend/src/api.py, frontend/public/contributions.html
=> backend, frontend: show contributions for a FAS username

frontend/src/app/contribute_events.cljs
Fix https://github.com/fedora-copr/logdetective/issues/239
=> frontend: send username if it was prefilled

backend/src/api.py, backend/src/store.py
=> Fix unicode errors in /contributions

frontend/public/js/offset.js, frontend/public/layout.html, frontend/src/app/components/snippets.cljs, frontend/src/app/helpers.cljs, frontend/src/app/review/core.cljs
Fix #235
Fix https://github.com/fedora-copr/logdetective/issues/241
Fix https://github.com/fedora-copr/logdetective/issues/242
=> Fix issues with snippet showing on incorrect lines

.pre-commit-config.yaml, backend/src/api.py, backend/src/constants.py, backend/src/data.py, backend/src/fetcher.py, backend/src/store.py, backend/tests/conftest.py, backend/tests/unit/test_fetcher.py, files/compile_extraction_dataset.py
Introducing ruff into pre-commit.
Typing issues should be addressed by https://github.com/fedora-copr/logdetective-website/pull/243 The line length is an interaction between ruff and flake8.
Depends-On: #243
=> Mass formatting files with ruff

openshift/log-detective.yaml
we are seeing OOMs, trying this first
=> double memory for our production pod

README.md
Fixes https://github.com/fedora-copr/logdetective/issues/219
Fixes #80
=> docs: how to submit annotations via API

openshift/log-detective.yaml
=> openshift: set persistent PVC to 6G

backend/src/api.py, backend/src/constants.py, backend/src/fetcher.py, backend/src/spells.py
Log handling has been modified to properly format and handle incoming messages. This is very similar to the setup we have in log detective server, only much simpler, since we don't need to handle logging to file and some aspects of configuration.
=> Expanding logging in the backend

frontend/public/css/style.css, frontend/public/index.html
We'll link our dataset on Hugging Face to show people what we have made so far.
New look:
=> Putting announcement about dataset on our webpage
