docker-compose.prod.yaml, docker/production/Dockerfile
Reverts 813c34b (PR #31)
We cannot have our production container listening on the port 80 because it is deployed in OpenShift and we can't use privileged ports there:
[2023-11-29 20:55:17 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-11-29 20:55:17 +0000] [1] [ERROR] Retrying in 1 second.
[2023-11-29 20:55:18 +0000] [1] [ERROR] Retrying in 1 second.
[2023-11-29 20:55:19 +0000] [1] [ERROR] Retrying in 1 second.
[2023-11-29 20:55:20 +0000] [1] [ERROR] Retrying in 1 second.
[2023-11-29 20:55:21 +0000] [1] [ERROR] Retrying in 1 second.
[2023-11-29 20:55:54 +0000] [1] [ERROR] Can't connect to ('0.0.0.0', 80)
Instead we want to have an OpenShift route from public 80 to container
8080. And I finally understand the point of PR #31, it was to fix the production container for docker-compose, so …
=> docker: change the production port back to 8080

frontend/src/app/homepage.cljs
Leading and trailing white space will be trimmed, before parameters are passed to the backend.
This should simplify copy and pasting of parameters into the search box.
=> Strip prefix and suffix whitespace chars from input parameters

backend/fetcher.py
#39 with that example build has no build to fetch - but instead of `There are no results...` response we got some weird traceback
Fixes #39
=> backend: dont pass NoneType to os.path.dirname in case baseurl is None

backend/api.py, backend/constants.py, backend/fetcher.py, backend/schema.py, backend/store.py, frontend/src/app/contribute.cljs, frontend/src/app/contribute_atoms.cljs, frontend/src/app/contribute_events.cljs, frontend/src/app/homepage.cljs, frontend/src/app/homepage_validation.cljs
Fix #24
Fix #34 
Fix #35
We collaborated on this PR with @nikromen
=> Support container logs

docker-compose.yaml, docker/frontend/Dockerfile, frontend/public/layout.html
That would install them only to initial source code built into the container image and wouldn't make them available for the bind-mounted sources during the container runtime. Please see more details in the code comment.
This commit fixes our `The required namespace "react" is not available, it was required by "reagent/core.cljs"` issue.
=> docker: don't preinstall JavaScript and ClojureScript dependencies

Makefile, backend/api.py, backend/spells.py, docker-compose.prod.yaml, docker-compose.yaml, docker/production/Dockerfile, files/env, frontend/public/index.html, openshift/README.md, openshift/log-detective.yaml
Fixes #49
This solution raises two concerns for the future once we have a
lot of data collected:
- it will be a while until the data will be tarred - creating delay before
actual download (after cca 200 feedbacks relly noticable delay :/)
look at example with only 300 (tiny!!) feedbacks:
```
[root@backend persistent]# time tar -zcf results.tar.gz results/
real m9.473s
user m9.328s
sys m0.483s
```
- downloading takes also some time
-> thus blocking the whole worker during this. IIRC we have 8 workers thus
8 downloads and API is unresponsive.
Solution:
- how to solve the delay before download:
https://github.com/fedora-copr/log-detective-website/issues/64
- the issue above is the slowest, once that will be resolved and people
still complain, do this: …
=> Download collected data

openshift/README.md, openshift/log-detective.yaml
- update docs on generating TLS LE certs
- create a new route for logdetective.com
- redirect http -> https
This is already deployed in prod 😇
Fixes #61
=> cert, openshift: accept both domains

backend/store.py
because of class constant logs were stored into one date, but store_to should change since it is not constant
=> backend: refresh datetime timestamp in Storator

Makefile, backend/constants.py, backend/fetcher.py
Cheers @FrostyX
https://github.com/fedora-copr/log-detective-website/issues/73#issuecomment-1889042206
Fixes #73
Verified and I was finally able to fetch the failed SRPM build log.
One problem though is that the build didn't have the spec file uploaded so I
had to change the logic with upload specs to not require one.
=> fix fetching SRPM build logs

.gitattributes, README.md, log_detective_demo.gif
Technically this does count as a large file.
Therefore it is now tracked by git-lfs[0] to simplify repo management. In practice it makes very little difference.
Now if it was 3GB, that would be a problem.
[0] https://git-lfs.com/
Co-authored-by: Jakub Kadlčík
=> Adding video demonstration

backend/fetcher.py
if a koji build fails, sadly this doesn't do anything:
koji_logs = self.client.getBuildLogs(self.build_or_task_id)
koji api docs:
> This method will only return logs for builds that are complete.
> If a build is in progress, failed, or canceled, you must look at the
> build's task logs instead (see listTaskOutput).
Instead, we need to manually traverse the task hierarchy and select the
right buildArch task, which this commit implements.
=> correctly obtain failed koji build logs

backend/fetcher.py
this is refactoring of the KojiProvider - we detect if the provided id
is build or task immediately in constructor
then we always get logs and spec from task
=> koji_provider: get spec file from task

backend/fetcher.py
from their SRPMs - this reintroduces the codebase
originally written by @nikromen, hence the co-authorship
If fetching of a spec file fails, return None instead of erroring out.
We want to have the annotated snippets and can live if a few don't have
spec files.
Fixes #98
=> download specs for koji scratch builds

files/compile_extraction_dataset.py, openshift/dataset-cron.yaml, openshift/log-detective.yaml
- cache_dir = /tmp since it's the only writable place
- always pull the latest image to be safe
- polish resource: 250MB is not enough for the script
=> cronjob fixes:

frontend/src/app/contribute.cljs, frontend/src/app/contribute_events.cljs
Fix #101
We are storing the value into `localStorage` instead cookies, so that nothing is on the server and we don't have to show the annoying "accept cookies" dialog.
https://www.w3schools.com/jsref/prop_win_localstorage.asp
=> frontend: remember the username and prefill it the next time

backend/store.py, frontend/public/css/style.css, frontend/public/documentation.html, frontend/src/app/homepage.cljs
This should improve UX of progress bar and make clear, what the progress display, what is 100% and links to documentation.
Note that this is completely untested as I unable to run pre-commit hook and neither run podman-compose (it again does not display the central box for me).
=> improve UX of progress bar

frontend/src/app/contribute_events.cljs, frontend/src/app/helpers.cljs
We have been collecting incorrect indexes. They aren't calculated from the end of the log but rather from the end of the previous node.
I am currently working on fixing our collected data.
=> frontend: always calculate the snippet indexes from the beginning

frontend/src/app/contribute.cljs
#126 shows that instructions do not match the actual workflow. This is to change the button text to match the instructions.
=> Updated add button text

Makefile, backend/src/api.py, backend/src/constants.py, backend/src/schema.py, backend/src/spells.py, backend/src/store.py, backend/tests/unit/test_store.py, files/env, frontend/public/css/style.css, frontend/public/layout.html, frontend/shadow-cljs.edn, frontend/src/app/components/accordion.cljs, frontend/src/app/components/jumbotron.cljs, frontend/src/app/components/snippets.cljs, frontend/src/app/contribute.cljs, frontend/src/app/contribute_atoms.cljs, frontend/src/app/contribute_events.cljs, frontend/src/app/contribute_logic.cljs, frontend/src/app/helpers.cljs, frontend/src/app/homepage.cljs, frontend/src/app/review/atoms.cljs, frontend/src/app/review/core.cljs, frontend/src/app/review/events.cljs, frontend/src/app/review/logic.cljs, frontend/src/app/three_column_layout/core.cljs, pylintrc
This should be more or less the final look of the review page.
Fixes: #4
=> Review page feature

backend/src/schema.py, docker/backend/Dockerfile, docker/frontend/Dockerfile, docker/production/Dockerfile
=> Migrate to f40

docker/backend/Dockerfile, docker/production/Dockerfile
=> docker: add standard uvicorn as dep to support websocket

.github/workflows/python-diff-lint.yml, backend/src/api.py
I had to rewrite the function from an async implementataion that stopped
working (probably after an update to fastapi and starlette).
Fixes: https://github.com/fedora-copr/log-detective-website/issues/157
=> Fix downloading results

.github/workflows/python-diff-lint.yml
The install_rpm_packages option accepts a list as a space-separated string.
=> ci: fix the vcs-diff-lint integration

frontend/src/app/components/snippets.cljs, frontend/src/app/review/atoms.cljs, frontend/src/app/review/core.cljs, frontend/src/app/review/events.cljs
Two unrelated changes in this PR:
- Fix for #166 
- Automatical scroll to selected snippets
=> Fix issue with not highlighted snippets and automatically scroll to snippets

.github/workflows/docker-publish.yml, Makefile, README.md, backend/README.md, docker-compose.prod.yaml, docker-compose.yaml, docker/frontend/Dockerfile, docker/production/Dockerfile, frontend/package-lock.json, frontend/package.json, frontend/public/layout.html, openshift/README.md, openshift/dataset-cron.yaml, openshift/log-detective.yaml
quay.io has a new namespace, we can start discussion on this proper.
=> Mass change of the name to logdetective

openshift/README.md, openshift/log-detective.yaml
All of these changes are now live. I had to revert a few rename changes because we still have the log-detective.com domain.
There was also a misconfiguration in the PVC. See commits for details.
=> Reflect our openshift configuration after the rename

frontend/src/app/review/core.cljs
Fixes #156
This will be useful for changing a location of a snippet, in case the new snippet should be over the previous one.
=> frontend: allow deleting snippets in review

backend/src/spells.py
Fix https://github.com/fedora-copr/logdetective-website/issues/165
Changed the folder inside the tarball to be called "results" instead of "results-<timestamp>.tar.gz"
=> Changed tarball folder name

.github/workflows/python-diff-lint.yml, README.md, backend/src/api.py, backend/src/constants.py
Add code to connect to the server and process it's output so that website is able to show this to the user.
Possible improvements:
- Easier way to set the environment variable to the docker-compose
- Better exception handling
- ~Add snippet log as separate server data so it could be correctly showed on the website~
- Add unit tests
I tried to found a better way than using local IP to connect two compose runs together. The issue is that docker-compose seems to be an isolated unit with no option to pass environment variable in or share one pod created by user.
=> Add server support to the backend

frontend/src/app/prompt/core.cljs
we only accept a URL right now
also contains:
> explain: comment out example buttons
> not implemented yet, so let's hide them
=> explain: update prompt description

backend/src/api.py, frontend/src/app/helpers.cljs, frontend/src/app/prompt/core.cljs
See https://github.com/fedora-copr/copr/issues/3583
=> feat: Automatically get explained response if URL can be provided

backend/src/api.py, backend/src/constants.py, files/env
Both connection and read timeouts are now parametrized, with defaults in code and in the env file.
=> Parametrizing Log Detective response timeouts

backend/src/api.py
In the Reasoning seciton of the explanation page, we list multiple snippets. Their text is correct but we use the comment from the first snippet for all snippets.
=> backend: don't use the first snippet comment for all snippets

frontend/public/layout.html
Prior to this commit the header bar linked to the code and issues of this website itself, rather than the Log Detective code. While technically correct, this is confusing and doesn't match the user intentions.
=> layout: Make header bar link to actual Log Detective code

frontend/src/app/prompt/core.cljs
This can help folks with triage a lot to see the full line when the
error value is usually at the end of the line.
This is a quick and dirty solution.
Addresses #209
Example:
It's kinda ugly but gets the job done IMO. I tried not to truncate the button but that just overflew outside of the window and was terrible.
=> Explain: print full log line with snippet body

frontend/src/app/helpers.cljs, frontend/src/app/homepage.cljs, frontend/src/app/prompt/core.cljs
Fix #210
This should fix the back and forward browser buttons on our explain page
=> Correct browser history for our explain page

backend/src/store.py
Fix https://github.com/fedora-copr/logdetective/issues/240
=> backend: don't fail for long URLs

frontend/shadow-cljs.edn
The options used [0] should put limits on both direct buffers and on heap. Together this should keep memory around 768MB.
[0] https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html
```
ID            NAME                              CPU %       MEM USAGE / LIMIT  MEM %       NET IO             BLOCK IO           PIDS        CPU TIME      AVG CPU %
5c8138af3d0c  log-detective-website_backend_1   0.16%       52.5MB / 67.1GB    0.08%       3.29kB / 1.048kB   98.3kB / 176.1kB   6           1.61788s      0.25%
3d8a7c2cdb66  log-detective-website_frontend_1  1.13%       779.3MB / 67.1GB   1.16%       57.09MB / 1.349MB  221.2kB / 54.62MB  125         1m45.860146s  16.35%
```
=> Limiting memory allocation to java runtime

backend/src/fetcher.py, backend/tests/unit/test_fetcher.py
This doesn't resolve https://github.com/fedora-copr/logdetective/issues/244 but it does at least allow for uploads of failed flatpak build logs.
=> Allowing submissions from koji flatpak builds

frontend/src/app/contribute.cljs
Since we had issues when we were deleting previously selected snippets outright, this change instead loosens conditional to check if `any` snippet has it's description filled. 
Originally reported: https://github.com/fedora-copr/logdetective/issues/285
=> Tick checkbox as long as at least one snippet has description

backend/src/api.py
The new fields to `OkResponse` introduced in #260 cause an error (#265).
This tries to fix it by allowing `OkResponse.review_id` to be either a
`str` or an `uuid.UUID`. This is for backwards compatibility when
reviews were just a timestamp. Remember, we need to handle those when
reviewing older contributions.
The `/frontend/review` endpoint now returns a properly filled
`OkRepsonse`. This part is the actual fix for #265.
=> Fix broken review page

frontend/src/app/contribute.cljs, frontend/src/app/contribute_atoms.cljs, frontend/src/app/contribute_events.cljs
Turns out we are already returning the link for review in our response. https://github.com/fedora-copr/logdetective-website/blob/main/backend/src/api.py#L252
=> Adding link to review of just submitted annotation

backend/src/api.py
Resolves #234 
While it would be possible to cover the exception in some way, it would be highly irregular. Missing log means that no analysis is possible. And therefore no successful response is possible.
=> Propagating exception and logging info

docker/production/Dockerfile, files/gunicorn.conf.py, openshift/log-detective.yaml
Configuration for production server is now in a separate file. I've also explicitly set number of workers, increased number of requests and jitter. Where possible, the values were derived from https://docs.gunicorn.org/en/stable/settings.html#config-file 
Note: 
For production image we are pulling repo and then using it in the image, rather than getting the source from local dir. 
This means that this change will fail, if you your try to run production deployment before it is merged. Awkward, but reasonable workaround is replace step cloning the original repo with:
```
RUN git clone https://github.com/jpodivin/log-detective-website.git /sr && \
cd /src && \
git checkout -b gunicornconfig origin/gunicornconfig
```
=> Moving production configuration into file
